import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      backgroundImage: {
        "gradient-jet": "var(--gradient-jet)",
        "gradient-onyx": "var(--gradient-onyx)",
        "gradient-yellow": "var(--gradient-yellow)",
        "gradient-yellow-2": "var(--gradient-yellow-2)",
        "text-gradient-yellow": "var(--text-gradient-yellow)",
        "border-gradient-onyx": "var(--border-gradient-onyx)",
      },
      borderRadius: {
        "8p": "0.5rem",
        "7p": "0.4375rem",
        "12p": "0.75rem",
        "14p": "0.875rem",
        "15p": "0.9375rem",
        "20p": "1.25rem",
        "30p": "1.875rem",
      },
      boxShadow: {
        "shadow-1": "var(--shadow-1)",
        "shadow-2": "var(--shadow-2)",
        "shadow-3": "var(--shadow-3)",
        "shadow-4": "var(--shadow-4)",
        "shadow-5": "var(--shadow-5)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        jet: "var(--jet)",
        onyx: "var(--onyx)",
        "onyx-75": "var(--onyx-75)",
        "eerie-black-1": "var(--eerie-black-1)",
        "eerie-black-2": "var(--eerie-black-2)",
        "smoky-black": "var(--smoky-black)",
        "white-1": "var(--white-1)",
        "white-2": "var(--white-2)",
        "orange-yellow-crayola": "var(--orange-yellow-crayola)",
        "vegas-gold": "var(--vegas-gold)",
        "light-gray": "var(--light-gray)",
        "light-gray-70": "var(--light-gray-70)",
        "bittersweet-shimmer": "var(--bittersweet-shimmer)",
      },
      fontSize: {
        "13p": "0.8125rem",
        "15p": "0.9375rem",
        "18p": "1.125rem",
      },
      screens: {
        xs: "320px",
        sm: "500px",
        md: "768px",
        lg: "1024px",
        xl: "1260px",
        "2xl": "1440px",
      },
      spacing: {
        "5p": "0.3125rem",
        "6p": "0.375rem",
        "7p": "0.4375rem",
        "8p": "0.5rem",
        "10p": "0.625rem",
        "14p": "0.875rem",
        "15p": "0.9375rem",
        "18p": "1.125rem",
        "20p": "1.25rem",
        "30p": "1.875rem",
        "40p": "2.5rem",
        "50p": "3.125rem",
        "60p": "3.75rem",
        "80p": "5rem",
        "120p": "7.5rem",
        "150p": "9.375rem",
        "275p": "17.1875rem",
        "420p": "26.25rem",
        "520p": "32.5rem",
        "700p": "43.75rem",
        "950p": "59.375rem",
        "1200p": "75rem",
      },
    },
  },
  plugins: [],
};
export default config;
